jardin_journal:
    path:     /journal
    defaults: { _controller: JardinBundle:Default:index }

jardin_add:
    path:     /ajouter
    defaults: { _controller: JardinBundle:Jardin:add }

jardin_update:
    path:     /update
    defaults: { _controller: JardinBundle:Jardin:update }

note_add:
    path:     /note/add/{jardinId}/{date}
    defaults: { _controller: JardinBundle:Note:add }
    options:
        expose: true

note_update:
    path:     /note/update
    defaults: { _controller: JardinBundle:Note:update }
    options:
        expose: true

note_delete:
    path:     /note/delete
    defaults: { _controller: JardinBundle:Note:delete }
    options:
        expose: true

note_view:
    path:     /note
    defaults: { _controller: JardinBundle:Note:view }

note_list:
    path:   /notelist
    defaults: {_controller: JardinBundle:Note:list }
