jardin_journal:
    path:     /journal
    defaults: { _controller: JardinBundle:Default:index }

jardin_add:
    path:     /ajouter
    defaults: { _controller: JardinBundle:Jardin:add }

jardin_update:
    path:     /update
    defaults: { _controller: JardinBundle:Jardin:update }

note_add:
    path:     /note/add/{jardinId}/{date}
    defaults: { _controller: JardinBundle:Note:add }
    options:
        expose: true

note_update:
    path:     /note/update
    defaults: { _controller: JardinBundle:Note:update }
    options:
        expose: true

note_delete:
    path:     /note/delete
    defaults: { _controller: JardinBundle:Note:delete }
    options:
        expose: true

note_view:
    path:     /note
    defaults: { _controller: JardinBundle:Note:view }
    options:
        expose: true

note_list:
    path:   /notelist
    defaults: {_controller: JardinBundle:Note:list }
    options:
        expose: true

plantt_add:
    path:     /plantt/add
    defaults: { _controller: JardinBundle:Plantation:add }
    options:
        expose: true

plantt_update:
    path:     /plantt/update
    defaults: { _controller: JardinBundle:Plantation:update }
    options:
        expose: true

plantt_delete:
    path:     /plantt/delete
    defaults: { _controller: JardinBundle:Plantation:delete }
    options:
        expose: true

plantt_list:
    path:     /plantt/list
    defaults: { _controller: JardinBundle:Plantation:list }
    options:
        expose: true

plantt_view:
    path:     /plantt/view
    defaults: { _controller: JardinBundle:Plantation:view }
    options:
        expose: true