evenement_homepage:
    path:     /index
    defaults: { _controller: EvenementBundle:Default:index }
ajouterev:
    path:     /ajouterev
    defaults: { _controller: EvenementBundle:Evenement:ajouterev }
modifev:
    path:     /modifev
    defaults: { _controller: EvenementBundle:Evenement:modifev }
pageev:
    path:     /page
    defaults: { _controller: EvenementBundle:Evenement:pageev }
evuser:
    path:     /evuser
    defaults: { _controller: EvenementBundle:Evenement:evuser }
consulter:
    path:     /consulter
    defaults: { _controller: EvenementBundle:Evenement:consulter }
participer:
    path:     /participer
    defaults: { _controller: EvenementBundle:Evenement:participer }
participerp:
    path:     /participerp
    defaults: { _controller: EvenementBundle:Evenement:participerp }
inviter:
    path:     /inviter
    defaults: { _controller: EvenementBundle:Evenement:inviter }