evenement_homepage:
    path:     /index
    defaults: { _controller: EvenementBundle:Default:index }
ajouterev:
    path:     /ajouterev
    defaults: { _controller: EvenementBundle:Evenement:ajouterev }
modifev:
    path:     /modifev
    defaults: { _controller: EvenementBundle:Evenement:modifev }
annulerev:
    path:     /annulerev
    defaults: { _controller: EvenementBundle:Evenement:annulerev }
confirmerev:
    path:     /confirmerev
    defaults: { _controller: EvenementBundle:Evenement:confirmerev }
propev:
    path:     /propev
    defaults: { _controller: EvenementBundle:Evenement:propev }
listev:
    path:     /listev
    defaults: { _controller: EvenementBundle:Evenement:listev }
pageev:
    path:     /page
    defaults: { _controller: EvenementBundle:Evenement:pageev }
evuser:
    path:     /evuser
    defaults: { _controller: EvenementBundle:Evenement:evuser }
consulter:
    path:     /consulter
    defaults: { _controller: EvenementBundle:Evenement:consulter }
participer:
    path:     /participer
    defaults: { _controller: EvenementBundle:Evenement:participer }
participerp:
    path:     /participerp
    defaults: { _controller: EvenementBundle:Evenement:participerp }
inviter:
    path:     /inviter
    defaults: { _controller: EvenementBundle:Evenement:inviter }
cal:
    path:     /cal
    defaults: { _controller: EvenementBundle:Evenement:cal }