evenement_homepage:
    path:     /index
    defaults: { _controller: EvenementBundle:Default:index }
ajouterev:
    path:     /ajouterev
    defaults: { _controller: EvenementBundle:Evenement:ajouterev }
modifev:
    path:     /modifev
    defaults: { _controller: EvenementBundle:Evenement:modifev }
afficherev:
    path: /afficherev
    defaults: { _controller: EvenementBundle:Evenement:affichierev }
pageev:
    path:     /page
    defaults: { _controller: EvenementBundle:Evenement:pageev }
evuser:
    path:     /evuser
    defaults: { _controller: EvenementBundle:Evenement:evuser }