preservation:
    resource: "@PreservationBundle/Resources/config/routing.yml"
    prefix:   /preservation

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /evenement

jardin:
    resource: "@JardinBundle/Resources/config/routing.yml"
    prefix:   /jardin

achat:
    resource: "@AchatBundle/Resources/config/routing.yml"
    prefix:   /panier

plante:
    resource: "@PlanteBundle/Resources/config/routing.yml"
    prefix:   /plante

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

list_user/admin:
    path:     /admin/list_user
    defaults: { _controller: AppBundle:User:list }

Modifier_etat_compte:
    path:     /admin/Modifier_etat_compte
    defaults: { _controller: AppBundle:User:etat }

consulter_membre:
    path:     /consulter_membre
    defaults: { _controller: AppBundle:User:consulter }

admin_home:
    path:     /admin/home
    defaults: { _controller: AppBundle:User:homeadmin }

profile_user:
    path:     /account
    defaults: {_controller: AppBundle:User:Account}

profile_settings:
    path:     /account/profile
    defaults: { _controller: AppBundle:User:settings }

profile_preferences:
    path:     /account/jardin
    defaults: { _controller: AppBundle:User:preferences }

profile_admin:
    path:     /admin/profile
    defaults: { _controller: AppBundle:User:profilead }

user_home:
    path:     /home
    defaults: { _controller: AppBundle:User:homemembre }

moderateur_home:
    path:     /moderateur/dashboard
    defaults: { _controller: AppBundle:User:homemoderateur }

Role_Membre:
    path:     /admin/Role_Membre
    defaults: { _controller: AppBundle:User:rolemembre }

Role_Moderateur:
    path:     /admin/Role_Moderateur
    defaults: { _controller: AppBundle:User:rolemoderateur }

list_user/moderateur:
    path:     /moderateur/list_user
    defaults: { _controller: AppBundle:User:listmembre }

Modifier_etat_compte_by_moderateur:
    path:     /moderateur/Modifier_etat_compte
    defaults: { _controller: AppBundle:User:etat }

chart:
    path:     /chart
    defaults: { _controller: AppBundle:Chart:chart }















