<?php

namespace EvenementBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\AST\Functions\CurrentDateFunction;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{


}