<?php
/**
 * Created by PhpStorm.
 * User: Bouazza Med
 * Date: 26/02/2019
 * Time: 17:26
 */

namespace EvenementBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\AST\Functions\CurrentDateFunction;

/**
 * ParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantsRepository extends \Doctrine\ORM\EntityRepository
{


}