forum_homepage:
    path:     /forum
    defaults: { _controller: ForumBundle:Default:index }

consulter_sujet:
    path:     /plante/sujet/consulter
    defaults: { _controller: ForumBundle:Sujet:consulter }




