forum_homepage:
    path:     /forum
    defaults: { _controller: ForumBundle:Default:index }

consulter_plante:
    path:     /plante/consulter
    defaults: { _controller: ForumBundle:Sujet:afficher }




