<?php

namespace PreservationBundle\Repository;

/**
 * EspaceDePreservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspaceDePreservationRepository extends \Doctrine\ORM\EntityRepository
{
}
