<?php

namespace JardinBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByDate($date,$jardin)
    {
        return $this->findBy([
            'dateN' => $date,
            'jardinId' => $jardin
        ]);
    }
}
