<?php

namespace JardinBundle\Repository;

/**
 * PlantationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantationRepository extends \Doctrine\ORM\EntityRepository
{
}
