<?php

namespace ForumBundle\Repository;

/**
 * ReactionReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReactionReponseRepository extends \Doctrine\ORM\EntityRepository
{
}
