<?php

namespace ForumBundle\Repository;

/**
 * ReactionSujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReactionSujetRepository extends \Doctrine\ORM\EntityRepository
{
}
