plante_homepage:
    path:     /index
    defaults: { _controller: PlanteBundle:Default:index }
planteadd:
    path:     /add
    defaults: { _controller: PlanteBundle:Plante:add }
planteaff:
    path:     /
    defaults: { _controller: PlanteBundle:Plante:aff }
plantedetaile:
    path:     /detaille
    defaults: { _controller: PlanteBundle:Plante:det }
conulter:
    path: /consulter
    defaults: { _controller: PlanteBundle:Plante:cons }
supprimer:
    path: /supprimer
    defaults: { _controller: PlanteBundle:Plante:supp }
modifier:
    path: /modifier
    defaults: { _controller: PlanteBundle:Plante:modif }
proposer:
    path: /proposer
    defaults: { _controller: PlanteBundle:Plante:prop }
propad:
    path: /propad
    defaults: { _controller: PlanteBundle:Plante:propad }
accepter:
    path: /accepter
    defaults: { _controller: PlanteBundle:Plante:acc }
filter:
    path: /filter
    defaults: { _controller: PlanteBundle:Plante:fil }
addpanier:
    path: /addpan
    defaults: { _controller: PlanteBundle:Plante:pan }
result:
    path: /resultat
    defaults: { _controller: PlanteBundle:Plante:res }
archive:
    path: /archive
    defaults: { _controller: PlanteBundle:Plante:arc }
archi:
    path: /archi
    defaults: { _controller: PlanteBundle:Plante:arch }